### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [fspoettel/thirtytwopixels#1]
Hello!

I found link to this project from https://hackaday.com/2020/10/11/lo-fi-art-on-a-32x32-matrix/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by fspoettel** [comment]
Hey @vazhnov! Thanks for opening the issue and also adding the link to hackaday :) wasn't aware of that.
I added the MIT license to the project

**Comment by vazhnov** [comment]
@fspoettel , thank you!
