### ISSUE TITLE
Works for sixtyfourpixels too

### ISSUE THREAD

**Issue by kylejohnsonkj** [fspoettel/thirtytwopixels#4]
Thanks for the great project. I'm using this to connect Spotify to my 64x64 matrix.

It would be nice if the display size could be centralized to one location. I had to change 32 to 64 in various places. Also adding options.cols = width to matrix_factory.py was necessary to get it to display right.

The fetches every half second caused some noticeable flickering as well (I'm running both client and server on the pi), so I backed it down to every 5 seconds. Which seems reasonable since it's running 24/7... at least I think?

Nonetheless, you saved me a ton of time tinkering. Appreciate it!

Side note: I don't know the Spotify API too well yet. Do you think it'd be possible to only send data to the matrix when Spotify is playing on the same wifi network or to a specific device?

**Comment by fspoettel** [comment]
I'm glad to hear the project has been helpful to you! :)

> It would be nice if the display size could be centralized to one location. I had to change 32 to 64 in various places. Also adding options.cols = width to matrix_factory.py was necessary to get it to display right.

Absolutely! I did not think about differently sized led panels. I would accept a PR to improve this.

> The fetches every half second caused some noticeable flickering as well (I'm running both client and server on the pi), so I backed it down to every 5 seconds. Which seems reasonable since it's running 24/7... at least I think?

Correct. I'm not happy that we need to poll here in the first place, Spotify is badly missing webhooks or a similar notification system. I thought about optimizing the polling logic but there are a lot of edge cases with tracks being skipped etc. 

Updating the LED panel is very CPU-intensive, doing significant I/O while it's rendering can lead to this flicker. There are some things that can help with this depending on your hardware. See this [guide](https://github.com/hzeller/rpi-rgb-led-matrix#cpu-use) in the readme of the led panel bindings we use. Reserving a core on a larger rpi might solve it (I'm using a Zero, so not an option). If you are using an adafruit bonnet, [this](https://github.com/hzeller/rpi-rgb-led-matrix#improving-flicker) could also help, although I don't know the procedure for the 64x64 matrix.

> Do you think it'd be possible to only send data to the matrix when Spotify is playing on the same wifi network or to a specific device?

Yes, I think so. The binding is currently calling the [currently playing track endpoint](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-the-users-currently-playing-track) for convenience. You could change this to call the [playback state endpoint](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-information-about-the-users-current-playback) which includes device info. Note that this endpoint requires a differently scoped access token.

**Comment by kylejohnsonkj** [comment]
Sure, when I find time for a decent solution I'll shoot you that PR.

Yeah the whole lack of websockets support is a real bummer. I saw [this project](https://spotify-connect-ws.netlify.app) which looked intriguing, but it would have to run on a separate server to add any benefit. 

I've done the hardware flickering mod and also set isolcpus=3 to reserve the core. I actually keep changing my setup. At first I sent the artwork from my PC to a flaschen-taschen server running on the pi. Then I switched it to work over airplay2 so I could select the matrix as an airplay destination, which was pretty slick, but Spotify stutters since it only supports v1. So basically, here I am. It seems good enough with the spacing I have between fetches now. 

I'll take a look at that endpoint. I guess if I think about it backwards, another way to do it would be to look from the pi's perspective if the playing device is on the wifi network before allowing the image to be set. But then again, do I really want to add more cpu usage?

**Comment by kirill301** [comment]
Hi! 

Trying to make it work for 64x64 matrix and it's almost there apart from one issue - it looks like it replicates the same line in both upper and lower part of the matrix. This happens both when I display album art and random images. Any idea how to troubleshoot/fix this? 
![photo_2022-06-09 12 53 51](https://user-images.githubusercontent.com/54167026/172932946-6a09a671-0f8a-4ab3-9b3d-01b97d7c9c07.jpeg)

I tried running demos with the original rpi-rgb-led-matrix project, and it didn't have that issue.
![photo_2022-06-09 12 57 07](https://user-images.githubusercontent.com/54167026/172933459-b2bac6b0-33be-40c8-b8f1-f5ddf660303d.jpeg)
